### ISSUE TITLE
Text Wrapping issues

### ISSUE THREAD

**Issue by FabioRosado** [opsdroid/opsdroid-desktop#16]
- The text is shown without any indentations and white spaces while.
- Long urls are shown outside the chat box

I've only tested the big chunk of text in the shell and opsdroid desktop connector. 

<img width="402" alt="screen shot 2017-09-13 at 07 28 52" src="https://user-images.githubusercontent.com/3131401/30363658-f5aef298-9858-11e7-9b09-d7d840d89800.png">

**Comment by bryanbraun** [comment]
I'll put together a fix for this one. 👍
