### ISSUE TITLE
Unable to start the application - Harfbuzz version too old

### ISSUE THREAD

**Issue by abhishekmadhu** [opsdroid/opsdroid-desktop#39]
Hi, 
I am trying to set up the opsdroid-desktop application, following the user guide [here](https://github.com/opsdroid/opsdroid-desktop#linux)

I downloaded the latest release, and followed the exact installation steps. 
I was able to correctly extract the files into `/etc/opsdroid-desktop` with no errors.

But when I try to run it, I get an error as follows:
```
abhishek@IP:~$ /etc/opsdroid-desktop/opsdroid-desktop
Gtk-Message: 19:02:59.896: Failed to load module "canberra-gtk-module"
(opsdroid-desktop:58271): Pango-ERROR **: 19:03:00.041: Harfbuzz version too old (1.3.1)
Trace/breakpoint trap (core dumped)
```
I did a little "Googling" and I could not come to a proper definitive solution to this one (probably because I am inexperienced with Node.js?), but I think this might have to do something with [this electron issue](https://github.com/electron/electron/issues/20348). 

Any ideas?

Thanks,
Ab

**Release file that I downloaded**: 
opsdroid-desktop-v0.2.7-linux-x64.tar.gz (the latest release [from here](https://github.com/opsdroid/opsdroid-desktop/releases/tag/v0.2.7))

**System Details**
OS: Ubuntu 20.04 LTS
Type: 64-bit
GNOME version: 3.36.2
Windowing System: X11

**Comment by jacobtomlinson** [comment]
Thanks for raising this. 

This project has slipped into a state of disrepair as we don't see many people using it. Folks often just use the shell connector for local testing.

We are also looking to move away from an electron based interface to [opsdroid-web](https://github.com/opsdroid/opsdroid-web) which is the same thing but viewed in a browser.

I'd be happy to review and merge PR contributions, but do not expect to put any time into this project going forwards.

**Comment by abhishekmadhu** [comment]
Understood. 
I would try using opsdroid-web.

Thanks.
